### ISSUE TITLE
Automatically generate mscgen chart

### ISSUE THREAD

**Issue by simard57** [mscgenjs/vscode-mscgen#2]
can a way to cast the mscgen code to a specified server site to return the mscgen chart graphic be added to the extension?

**Comment by sverweij** [comment]
No such server exists to the best of my knowledge.

Even if it was - this vscode plugin is just doing syntax highlighting. I've been playing with making a previewer for vscode as well, but decided against it. I don't use vscode that often and writing plugins for it is not a pleasant experience.

### alternatives
I gather you're looking for an easy way to preview a sequence chart as you type, or to even generate one for permanent use later on (check?).

Here are some alternatives that work (all outside vscode):
- There's the [mscgen-preview](https://atom.io/packages/mscgen-preview) package for the atom editor. It's my goto if I need to write a sequence chart.
- At [mscgen.js.org](https://mscgen.js.org) you can find an on line editor for mscgen and its brethren.
- There's a [command line version of mscgenjs](https://github.com/mscgenjs/mscgenjs-cli) which you can install with npm (`npm install --global mscgenjs-cli`)
